color = ''
project-name = 'default'

[default]
account_id = 'acct_1QVJ3jHs4q3jg2YI'
device_name = 'milena-Aspire-A515-45'
display_name = 'INTERACTIPLAY'
live_mode_api_key = 'rk_live_***********************************************************************************************iV4m'
live_mode_key_expires_at = '2025-11-22'
live_mode_pub_key = 'pk_live_51QVJ3jHs4q3jg2YI1Cdf3dYkmcSI0XDaxJV5sBta5xDG0RbBFFdIvfPRBpqOfaobAv2uj2zUeVbf1atWrjfMOZhV00gKsUvBux'
test_mode_api_key = 'sk_test_51QVJ3jHs4q3jg2YI9jtptufPPx0tbiQhSP2XFPALbgizANEzMMHtbOa4Q9RbvKG36dxoF3dSdIz0WIj8w57Rr98000ZKyO3Wl5'
test_mode_key_expires_at = '2025-11-22'
test_mode_pub_key = 'pk_test_51QVJ3jHs4q3jg2YIk36pOok4c77vve3s5yqhBT7MVXmYxwmS7lbMjBWV7qHg6vbVI9JQL3wh9z2ymlmmSoyNupbb00exhYaAMX'
