-- CreateTable
CREATE TABLE "public"."plans" (
    "ID" TEXT NOT NULL,
    "PLAN" TEXT NOT NULL,
    "STRIPE_PLAN_ID" TEXT NOT NULL,
    "STRIPE_PLAN_PRICE" TEXT NOT NULL,
    "PRICE" DOUBLE PRECISION NOT NULL,
    "STATUS" BOOLEAN NOT NULL DEFAULT true,
    "PLAYS" INTEGER NOT NULL,
    "PLAYS_PRICE" DOUBLE PRECISION NOT NULL,
    "VIDEO_LIMIT" INTEGER NOT NULL,

    CONSTRAINT "plans_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."users" (
    "ID" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "PHONE" TEXT NOT NULL,
    "AVATAR" TEXT NOT NULL DEFAULT '/padrao',
    "HASHED_PASSWORD" TEXT NOT NULL,
    "HASHED_TOKEN" TEXT,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "FIRST_ACESS" BOOLEAN NOT NULL DEFAULT true,
    "VALIDATION_EMAIL" BOOLEAN NOT NULL DEFAULT false,
    "ROLE" TEXT NOT NULL DEFAULT 'client',
    "ACTIVE" BOOLEAN NOT NULL DEFAULT false,
    "STRIPE_CUSTOMER_ID" TEXT,
    "STRIPE_SUBSCRIPTON_ID" TEXT,
    "STRIPE_SUBSCRIPTON_STATUS" TEXT,
    "PLAN_ID" TEXT,

    CONSTRAINT "users_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."history_plays" (
    "ID" TEXT NOT NULL,
    "QTD_PLAYS" INTEGER NOT NULL DEFAULT 0,
    "PRICE_MONTH" DOUBLE PRECISION,
    "STATUS" TEXT DEFAULT 'ativo',
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "USER_ID" TEXT,

    CONSTRAINT "history_plays_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."videos" (
    "ID" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "SIZE" INTEGER NOT NULL,
    "FORMAT" TEXT NOT NULL,
    "DURATION" INTEGER NOT NULL,
    "ORIENTATION" TEXT NOT NULL DEFAULT 'landscape',
    "HEIGHT" INTEGER NOT NULL,
    "WIDTH" INTEGER NOT NULL,
    "URL" TEXT NOT NULL,
    "USER_ID" TEXT,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "videos_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."campaigns" (
    "ID" TEXT NOT NULL,
    "NAME" TEXT NOT NULL DEFAULT 'campanha-${uuid()}',
    "EMBED_JS" TEXT,
    "EMBED_IFRAME" TEXT,
    "CORS" TEXT NOT NULL DEFAULT '*',
    "FEATURE_ID" TEXT,
    "USER_ID" TEXT,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "campaigns_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."analytics" (
    "ID" TEXT NOT NULL,
    "CAMPAIGN_ID" TEXT,
    "PLAYS_UNIQUE" INTEGER NOT NULL DEFAULT 0,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "analytics_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."views" (
    "ID" TEXT NOT NULL,
    "ANALYTICS_ID" TEXT,
    "DEVICE" TEXT NOT NULL,
    "BROWSER" TEXT NOT NULL,
    "TIMEZONE" INTEGER NOT NULL,
    "VIEW" INTEGER NOT NULL DEFAULT 0,
    "PLAYS" INTEGER NOT NULL DEFAULT 0,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "views_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."test_ab" (
    "ID" TEXT NOT NULL,
    "CAMPAIGN_ID_A" TEXT,
    "CAMPAIGN_ID_B" TEXT,
    "ANALYTICS_ID_A" TEXT,
    "ANALYTICS_ID_B" TEXT,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "test_ab_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."campaign_videos" (
    "ID" TEXT NOT NULL,
    "CAMPAIGN_ID" TEXT,
    "VIDEO_ID" TEXT,
    "ORDER" INTEGER NOT NULL DEFAULT 1,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "campaign_videos_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."bond_videos" (
    "ID" TEXT NOT NULL,
    "CAMPAIGN_VIDEO_ID" TEXT,
    "BOND_ID" TEXT,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "bond_videos_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."bonds" (
    "ID" TEXT NOT NULL,
    "VIDEO_ID" TEXT,
    "BUTTON" BOOLEAN NOT NULL DEFAULT false,
    "BUTTON_TEXT" TEXT,
    "BUTTON_CLICK" INTEGER NOT NULL DEFAULT 0,
    "BUTTON_STYLE" TEXT,
    "BUTTON_START" INTEGER NOT NULL DEFAULT 0,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "bonds_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."features" (
    "ID" TEXT NOT NULL,
    "AUTO_PLAY_ID" TEXT,
    "THUMB_ID" TEXT,
    "GANCHO_ID" TEXT,
    "TIMELINE_ID" TEXT,
    "EXTERNAL_LINK_ID" TEXT,
    "PIXEL_ID" TEXT,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "features_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."auto_play" (
    "ID" TEXT NOT NULL,
    "ATIVE" BOOLEAN NOT NULL DEFAULT false,
    "SECOND" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "auto_play_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."thumbs" (
    "ID" TEXT NOT NULL,
    "URL" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "thumbs_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."ganchos" (
    "ID" TEXT NOT NULL,
    "URL" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ganchos_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."timelines" (
    "ID" TEXT NOT NULL,
    "HEIGHT" INTEGER NOT NULL,
    "COR" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "timelines_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."external_videos" (
    "ID" TEXT NOT NULL,
    "START" INTEGER NOT NULL,
    "DURATION" INTEGER NOT NULL,
    "STYLE" TEXT NOT NULL,
    "URL" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "external_videos_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "public"."pixels" (
    "ID" TEXT NOT NULL,
    "NAME_META" TEXT,
    "ID_META" TEXT,
    "NAME_GOOGLE" TEXT,
    "ID_GOOGLE" TEXT,
    "LABEL_CONVERSION_GOOGLE" TEXT,
    "SHOOTING_EVENT_GOOGLE" TEXT,
    "SHOOTING_EVENT_VALUE_GOOGLE" DOUBLE PRECISION,
    "CREATED_AT" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "pixels_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "plans_STRIPE_PLAN_ID_key" ON "public"."plans"("STRIPE_PLAN_ID");

-- CreateIndex
CREATE UNIQUE INDEX "users_EMAIL_key" ON "public"."users"("EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "users_STRIPE_CUSTOMER_ID_key" ON "public"."users"("STRIPE_CUSTOMER_ID");

-- CreateIndex
CREATE UNIQUE INDEX "campaigns_FEATURE_ID_key" ON "public"."campaigns"("FEATURE_ID");

-- CreateIndex
CREATE UNIQUE INDEX "analytics_CAMPAIGN_ID_key" ON "public"."analytics"("CAMPAIGN_ID");

-- CreateIndex
CREATE UNIQUE INDEX "bond_videos_BOND_ID_key" ON "public"."bond_videos"("BOND_ID");

-- CreateIndex
CREATE UNIQUE INDEX "features_AUTO_PLAY_ID_key" ON "public"."features"("AUTO_PLAY_ID");

-- CreateIndex
CREATE UNIQUE INDEX "features_THUMB_ID_key" ON "public"."features"("THUMB_ID");

-- CreateIndex
CREATE UNIQUE INDEX "features_GANCHO_ID_key" ON "public"."features"("GANCHO_ID");

-- CreateIndex
CREATE UNIQUE INDEX "features_TIMELINE_ID_key" ON "public"."features"("TIMELINE_ID");

-- CreateIndex
CREATE UNIQUE INDEX "features_EXTERNAL_LINK_ID_key" ON "public"."features"("EXTERNAL_LINK_ID");

-- CreateIndex
CREATE UNIQUE INDEX "features_PIXEL_ID_key" ON "public"."features"("PIXEL_ID");

-- CreateIndex
CREATE UNIQUE INDEX "external_videos_URL_key" ON "public"."external_videos"("URL");

-- AddForeignKey
ALTER TABLE "public"."users" ADD CONSTRAINT "users_PLAN_ID_fkey" FOREIGN KEY ("PLAN_ID") REFERENCES "public"."plans"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."history_plays" ADD CONSTRAINT "history_plays_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "public"."users"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."videos" ADD CONSTRAINT "videos_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "public"."users"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."campaigns" ADD CONSTRAINT "campaigns_FEATURE_ID_fkey" FOREIGN KEY ("FEATURE_ID") REFERENCES "public"."features"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."campaigns" ADD CONSTRAINT "campaigns_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "public"."users"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."analytics" ADD CONSTRAINT "analytics_CAMPAIGN_ID_fkey" FOREIGN KEY ("CAMPAIGN_ID") REFERENCES "public"."campaigns"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."views" ADD CONSTRAINT "views_ANALYTICS_ID_fkey" FOREIGN KEY ("ANALYTICS_ID") REFERENCES "public"."analytics"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."test_ab" ADD CONSTRAINT "test_ab_CAMPAIGN_ID_A_fkey" FOREIGN KEY ("CAMPAIGN_ID_A") REFERENCES "public"."campaigns"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."test_ab" ADD CONSTRAINT "test_ab_CAMPAIGN_ID_B_fkey" FOREIGN KEY ("CAMPAIGN_ID_B") REFERENCES "public"."campaigns"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."test_ab" ADD CONSTRAINT "test_ab_ANALYTICS_ID_A_fkey" FOREIGN KEY ("ANALYTICS_ID_A") REFERENCES "public"."analytics"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."test_ab" ADD CONSTRAINT "test_ab_ANALYTICS_ID_B_fkey" FOREIGN KEY ("ANALYTICS_ID_B") REFERENCES "public"."analytics"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."campaign_videos" ADD CONSTRAINT "campaign_videos_CAMPAIGN_ID_fkey" FOREIGN KEY ("CAMPAIGN_ID") REFERENCES "public"."campaigns"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."campaign_videos" ADD CONSTRAINT "campaign_videos_VIDEO_ID_fkey" FOREIGN KEY ("VIDEO_ID") REFERENCES "public"."videos"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."bond_videos" ADD CONSTRAINT "bond_videos_CAMPAIGN_VIDEO_ID_fkey" FOREIGN KEY ("CAMPAIGN_VIDEO_ID") REFERENCES "public"."campaign_videos"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."bond_videos" ADD CONSTRAINT "bond_videos_BOND_ID_fkey" FOREIGN KEY ("BOND_ID") REFERENCES "public"."bonds"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."bonds" ADD CONSTRAINT "bonds_VIDEO_ID_fkey" FOREIGN KEY ("VIDEO_ID") REFERENCES "public"."videos"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."features" ADD CONSTRAINT "features_AUTO_PLAY_ID_fkey" FOREIGN KEY ("AUTO_PLAY_ID") REFERENCES "public"."auto_play"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."features" ADD CONSTRAINT "features_THUMB_ID_fkey" FOREIGN KEY ("THUMB_ID") REFERENCES "public"."thumbs"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."features" ADD CONSTRAINT "features_GANCHO_ID_fkey" FOREIGN KEY ("GANCHO_ID") REFERENCES "public"."ganchos"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."features" ADD CONSTRAINT "features_TIMELINE_ID_fkey" FOREIGN KEY ("TIMELINE_ID") REFERENCES "public"."timelines"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."features" ADD CONSTRAINT "features_EXTERNAL_LINK_ID_fkey" FOREIGN KEY ("EXTERNAL_LINK_ID") REFERENCES "public"."external_videos"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."features" ADD CONSTRAINT "features_PIXEL_ID_fkey" FOREIGN KEY ("PIXEL_ID") REFERENCES "public"."pixels"("ID") ON DELETE SET NULL ON UPDATE CASCADE;
