import type { Metadata } from "next";
import "./globals.scss";
import { IsMobileProvider } from "@/context/isMobileContext";
import Menu from "@/components/Menu";
import Help from "@/components/Help";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Interactiplay - Plataforma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <IsMobileProvider>
        <body>
          <Menu />
          <Help />
          {children}
          <Footer />
        </body>
      </IsMobileProvider>
    </html>
  );
}
